# Generated by Django 4.2.9 on 2024-01-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_script_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="script",
            old_name="text",
            new_name="structured_text",
        ),
        migrations.AddField(
            model_name="script",
            name="unstructured_text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
