# Generated by Django 4.2.9 on 2024-01-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_text_script_structured_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="end_index",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="start_index",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
