# Generated by Django 4.2.9 on 2024-01-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_comment_end_index_comment_start_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="source_text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
